pipeline:
  docker:
    image: plugins/docker
    repo: kinadu/inline-wiki
    tags: latest
    secrets: [ docker_username, docker_password ]
  kubernetes:
    image: gcr.io/google_containers/hyperkube-amd64:v1.9.2
    commands:
      - UPDATE_AT=`date +%s`
      - kubectl patch deployment node-wiki -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"force-update.inajob-tk/updated-at\":\"$UPDATED_AT\"}}}}}"
    secrets: [ kube_server, kube_token, kube_ca ]
